src/client/client.js, src/store/store-request-sender.js, src/store/url-helper.js, src/store/v2/mappers/index.js, test/client/client.spec.js, test/mocks/store-instrument-data.js, test/store/store-request-sender.spec.js, test/store/url-helper.spec.js, test/store/v2/mappers/index.spec.js
Adds the ability to Post a trusted shipping address and retrieve a list of instruments.
[Bigpay API](https://github.com/bigcommerce/api-schema/blob/master/bigpay/v2/docs/payments.yaml)
Allow a shipper to checkout with a stored credit card and avoid providing a cvv if the shipping address is 'trusted'.
ping @davidchin @supercrabtree @bigcommerce/payments
=> feat(store): PAYMENTS-2672 Allow consumers to post a trusted shipping address

src/client/client.js, src/store/store-request-sender.js, src/store/url-helper.js, test/client/client.spec.js, test/mocks/store-instrument-data.js, test/store/store-request-sender.spec.js
Rename the following methods
`getShopperInstruments` -> `loadInstruments`
`postTrustedShippingAddress` -> `loadInstrumentsWithAddress`
For clarity and consistency with the sdk 
unit
=> refactor(client): PAYMENTS-2672 Rename vaulting endpoints

src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
Add a mapper to send the data to big pay with the structure that chasepay needs.
We need to send the data with a different structure that isn't supported by the mapper that already exist.
NOTE: This PR has a dependency with https://github.com/rodna-bc/checkout-sdk-js/tree/INT-275 of @rodna-bc 
@bigcommerce/payments  @bigcommerce/checkout
=> feat(payments): INT-275 Add a mapper for Cryptogram Payment instrument

src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
Adds `credit_card_number_confirmation` as part of the vaulting payment payload
When a stored credit card is not trusted, we ask the shopper to verify their credit card number.
The card number will then be passed to bigpay along with the bigpay_token and CVV for verification.
Unit
=> feat(payment): PAYMENTS-2675 Add CCNo. as part of the vaulting payment payload

src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
Add accountMask field to mapToCryptogram function.
To be able to send accountMask to bigPay.
@bigcommerce/payments 
@bigcommerce/integrations
=> feat(payment): INT-594 Send ChasePay CheckoutData needed for WePay

src/payment/v1/payment-mappers/payment-mapper.js, test/mocks/payment-request-data.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
- Look at payment form `checkout-sdk` for `deviceSessionId` 
- `quoteMeta` has been removed
Updated tests, now passing :) 
ping @bigcommerce/payments @icatalina
=> fix(payments): PAYMENTS-3064 Use deviceSessionId from payment

src/payment/payment-method-ids.js, src/payment/payment-method-mappers/payment-method-id-mapper.js, test/payment/payment-method-mappers/payment-method-id-mapper.spec.js
To support Google Pay when a purchase, we need to add as a paymentMethod of Braintree to be mapped correctly to BigPay
It needs to complete a E2E purchase using Google Pay + Braintree
ping @bigcommerce/payments @bigcommerce/integrations
=> INT-835 Add Google Pay to be supported as a payment method of braintree

package-lock.json, package.json, src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
- Update payment-mapper.js to take method value from `paymentMethod.method` instead of `payment.method` object.
- Fix gulp dependency not found in package.json
We need to keep track of the payment method used for payment providers which have wallets in a general way.
`paymentMethod.method` and `method` from the `data` payload refer to the same value, however the `paymentMethod.method` value is set automatically by the consumer i.e checkout-sdk-js
[BIGPAY#1549](https://github.com/bigcommerce/bigpay/pull/1549)
[BIGPAY#1552](https://github.com/bigcommerce/bigpay/pull/1552)
ping @bigcommerce/payments @bigcommerce/integrations
=> fix(payments): INT-1360 payment-mapper take method value from paymentMethod object

src/store/store-request-sender.js, src/store/url-helper.js, test/store/store-request-sender.spec.js, test/store/url-helper.spec.js
Remove the currency code requirement on the InstrumentsID url, where the ID is sufficient enough for what is intended.
Unnecessary. Discussed with @capsula4 that it would be better without the currency code when we already pass in the ID.
Specs updated.
https://github.com/bigcommerce/checkout-sdk-js/pull/567
=> fix(payments): PAYMENTS-4228 remove currency code for when ID exists

src/payment/v1/payment-mappers/payment-mapper.js, src/typedefs.js, test/mocks/payment-request-data.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
Add `three_d_secure` parameter as item to the credit card payload
To be able to send 3DS information within the credit card payload and process it by `bigpay`
ping @bigcommerce/checkout @bigcommerce/payments
=> feat(payments): INT-1479 Add three_d_secure to CreditCardInstrument payload

src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
[INT-1650](https://jira.bigcommerce.com/browse/INT-1650)
In `payment-mapper` I added new properties for vaulting in CBYS.
It is needed to map that data to bigpay.
@bigcommerce/payments @bigcommerce/intersys-integrations
=> feat(payments): INT-1650 adding properties to vaulting object

src/client/client.js, src/payment/payment-intent-generator.js, src/payment/url-helper.js, src/payment/v2/payment-mappers/payment-intent-mapper.js, test/client/client.spec.js, test/payment/payment-intent-generator.spec.js, test/payment/url-helper.spec.js, test/payment/v2/payment-mappers/payment-intent-mapper.spec.js
[INT-1577](https://jira.bigcommerce.com/browse/INT-1577)
We added a new endpoint to generate Payment Intents from Stripe, also the mappers and all files that were needed
Because the existing endpoint (ClientToken) is not supporting an specific fields that we need to handle vaulting into Stripe V3 (using payment intents) 
- [Checkout-sdk-js](https://github.com/bigcommerce/checkout-sdk-js/pull/620)
- [NGCheckout](https://github.com/bigcommerce-labs/ng-checkout/pull/1282)
- [BigPay](https://github.com/bigcommerce/bigpay/pull/1730)
@bigcommerce/intersys-integrations @bigcommerce/checkout
=> INT-1577 Support Stored Credit Card (vaulting) for Stripe V3

src/client/client.js, src/store/store-request-sender.js, test/client/client.spec.js, test/store/store-request-sender.spec.js
Remove the POST instrument method
We do not have an api to respond to these requests. 
```
${this.host}/api/v2/stores/${storeId}/shoppers/${customerId}/instruments
```
Unit
=> fix(instruments): PAYMENTS-4759 Remove POST instrument for api/v2

src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
As per title
We want to remove the mappers in bigpay, the proposed solution uses a new key within the payment object to indicate to this client it is safe to dump the whole content in the request to bigpay.
- Unit
=> PAYMENTS-4616 Allow a passthrough for payment data

src/store/url-helper.js, test/store/url-helper.spec.js
* Include new instrument types as part of the response. They need to be
handled by the consumer.
- Include all instruments as part of `loadInstruments`/`loadInstrumentsWithAddress`
- Up until now these two methods only returned credit card instruments. From now onwards the endpoint might also return accounts. Consumers of this library need to take this into account and handle the new instrument types correctly.
- Unit
ping @bigcommerce/checkout @bigcommerce/payments
=> PAYMENTS-4759 Include new instrument types in the response

src/store/store-request-sender.js, src/store/url-helper.js, test/store/store-request-sender.spec.js, test/store/url-helper.spec.js
When deleting a stored credit card from "Manage" in the checkout, the frontend should also send currency with the request to BigPay. The `?currency_code=...` parameter should be added to the request.
When using the "Manage Cards" modal in checkout to delete a stored card, it doesn't include the transactional currency code with the request. This means that we can't be sure that we're fetching the correct config to use to remove the card.
Screenshots
**Before**
**After**
ping @bigcommerce/payments
=> fix(vaulting): PAYMENTS-4820 Add currency to checkout request to delete a stored card

src/payment/offsite-payment-mappers/payload-mapper.js, test/payment/offsite-payment-mappers/payload-mapper.spec.js
Allow formattedPayload to be mapped on the offsite flow.
so additional info can be sent to bigpay when required.
ping @bigcommerce/checkout @bigcommerce/payments @bigcommerce/intersys-integrations
=> feat(payments): INT-1778 Allow formattedPayload to be mapped on the offsite flow

src/payment/v1/payment-mappers/order-mapper.js, test/mocks/payment-request-data.js, test/payment/v1/payment-mappers/order-mapper.spec.js
send shipping transit time to bigpay
So we can send it to providers who can make fraud decisions using the transit time
Updated unit test
ping @bigcommerce/payments
=> PAYMENTS-4848 send shipping transit time to bigpay

src/payment/offsite-payment-mappers/customer-mapper.js, test/payment/offsite-payment-mappers/customer-mapper.spec.js
Allow the field `customer_id` to be sent to bigpay when performing an offsite payment flow.
Customer_id is a field required for the vaulting flow, it's sent by the regular payload mapper but not by the offsite payload mapper.
https://github.com/bigcommerce/checkout-sdk-js/pull/742
https://github.com/bigcommerce/checkout-js/pull/176
Request sent to bigpay:
ping @bigcommerce/intersys-integrations @bigcommerce/checkout
=> feat(instrument): INT-1780 Map customer id in offsite payment mapper

package-lock.json, package.json, src/client/client.js, src/payment/offsite-payment-initializer.js, test/client/client.spec.js, test/payment/offsite-payment-initializer.spec.js
Add the target attribute as an optional parameter to build the form.
To be able to display the response in a named iframe.
[4] [bigcommerce/checkout-js](https://github.com/bigcommerce/checkout-js/pull/155) depends on:
[3] [bigcommerce/checkout-sdk-js](https://github.com/bigcommerce/checkout-sdk-js/pull/732) depends on:
[2] THIS PR depends on:
[1] [bigcommerce/form-poster-js](https://github.com/bigcommerce/form-poster-js/pull/9)
ping @bigcommerce/payments @bigcommerce/intersys-integrations
=> feat(payments): INT-1997 Add optional target parameter

src/payment/payment-method-ids.js, src/payment/payment-method-mappers/payment-method-id-mapper.js, test/payment/payment-method-mappers/payment-method-id-mapper.spec.js
Add paypalcommerce to payment methods
Because of the way Paypal Credit on Paypal Commerce is expected to be received by BigPay (like braintree). Bigpay should get "gateway: 'paypalcommerce'" (not 'paypalcommercecredit')
...
=> feat(payments): PAYPAL-293 Add paypalcommerce to payment methods

src/payment/v1/payment-mappers/payload-mapper.js
For credit card payment, after checkout sdk sends payment payload to BigPay, if `human_verification_required` response is returned from BigPay, Google Recaptcha instance is created to verify that the shopper is a human. It's invisible if Google thinks the shopper is human, and shows a challenge if Google thinks the shopper is a bot. 
Once ReCAPTCHA is completed, it'll re-send the payment request to BigPay with almost the same payload, except for a new `additional_action` property including the additional token that was just created when completing the ReCAPTCHA.
Sibling PR on checkout-sdk-js: https://github.com/bigcommerce/checkout-sdk-js/pull/875
To protect our stores from spammers using long lists of credit cards number to place fraudulent orders.
Screen records
**Visible Recaptcha** …
=> feat(payment): PAYMENTS-5425 Update payload-mapper for Carding remediation solution

src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
add `set_as_default_vaulted_instrument` mapping
map incoming `setAsDefaultInstrument` payloads to `set_as_default_stored_instrument`
to allow the checkout-sdk to send flags of `setAsDefaultInstrument` during payments, which this code remaps and sends on to the API as `set_as_default_stored_instrument` - in order to achieve the users objective of making that instrument their default going forward
unit tests
=> feat(payment): PAYMENTS-5513 add set_as_default_stored_instrument

src/payment/v1/payment-mappers/payment-mapper.js, test/mocks/payment-request-data.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
Send an additional field when making credit card payment
See above
Unit
=> CHECKOUT-4973: Add hosted_form_nonce to payment request object

src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
rename setAsDefaultInstrument to shouldSetAsDefaultInstrument (JS client facing change, not Payments API facing)
to move more inline with the standard set in `checkout-sdk-js`
passing tests
=> feat(payments): PAYMENTS-5513 rename setAsDefaultInstrument to shouldSetAsDefaultInstrument

src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
When paying with a stored instrument, forward the payment method nonce for the purpose of card verification. 
When using Braintree hosted fields, the client app only has access to tokenised credit card information. So we can only forward that to the server for verification.
Unit
=> CHECKOUT-4947: Forward payment method nonce when paying with stored instrument for card verification

src/payment/payment-method-ids.js, src/payment/payment-method-mappers/payment-method-id-mapper.js, test/payment/payment-method-mappers/payment-method-id-mapper.spec.js
Add paypalcommercecreditcards to PaymentMethodIdMapper
Because of the way Paypal Credit Cards on Paypal Commerce is expected to be received by BigPay (like braintree). Bigpay should get "gateway: 'paypalcommerce'" (not 'paypalcommercecreditcards')
Unit
=> PAYPAL-202 Add paypalcommercecreditcards to PaymentMethodIdMapper

src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
Include `hosted_form_nonce` in the request payload for stored payment instruments.
So that it can be used for validation.
Unit + Manual
=> CHECKOUT-5324: Send hosted form nonce when paying with stored payment instrument

src/payment/offsite-payment-mappers/payload-mapper.js, test/payment/offsite-payment-mappers/payload-mapper.spec.js
Send tax information on the offsite flow
Tax information is necessary to be sent by BlueSnapV2 
ping @bigcommerce/checkout @bigcommerce/payments @bigcommerce/intersys-integrations
=> feat(payments): INT-4188 Send tax information on the offsite flow

src/payment/v1/payment-mappers/payment-mapper.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
add browser_info to credit_card for Opayo
In order to authenticate shoppers via 3DS2 or 3DS1 when they checkout using Opayo Direct so that can be adhere to PSD2 regulation
[CHECKOUT-SDK-JS](https://github.com/bigcommerce/checkout-sdk-js/pull/1331)
@bigcommerce/apex-integrations @bigcommerce/checkout
=> feat(payments): INT-4969  add browser_info to credit_card for Opayo

src/payment/payment-method-types.js, src/payment/payment-submitter.js, src/payment/payment-types.js, src/payment/ppsdk/payment-mappers/ppsdk-payload-mapper.js, src/payment/url-helper.js, test/payment/payment-submitter.spec.js, test/payment/ppsdk/payment-mappers/ppsdk-payload-mapper.spec.js, test/payment/url-helper.spec.js
Update `PaymentSubmitter` to use the new PPSDK endpoint in case of PPSDK payment.
Also, create a new `PpsdkPayloadMapper` to match the [the new schema](https://github.com/bigcommerce/api-schema/blob/master/bigpay/payments.yaml).
**Note:** 
- Using the new endpoint for SDK credit card payments is behind an experiment `PAYMENTS-6514.integration_type_and_initialisation_strategy`
- Future updates to the PPSDK payment payload transformer may be needed.
Needed for the PPSDK payment sub-strategy on checkout.
Unit tests
ping @bigcommerce/payments 
ping @bigcommerce/checkout
=> feat(payments): PAYMENTS-7706 Update the payment submitter to use the PPSDK endpoint

src/payment/payment-method-ids.js, src/payment/payment-method-mappers/payment-method-id-mapper.js, test/payment/payment-method-mappers/payment-method-id-mapper.spec.js
A separate module was created for the Venmo payment method on the backend side. The common button strategy for all PPCP SPBs has now been expanded. In the future, a separate strategy will be created for each spb, including for Venmo. These tasks are already planned.
We need a module for the Venmo payment method to create separate button strategy for it
https://github.com/bigcommerce/bigpay/pull/5495
https://github.com/bigcommerce/bigcommerce/pull/46631
https://github.com/bigcommerce/checkout-js/pull/891
https://github.com/bigcommerce/checkout-sdk-js/pull/1458
New approach
Old approach
=> feat(payment): PAYPAL-1487 add PayPal Commerce Venmo

src/payment/payment-method-ids.js, src/payment/payment-method-mappers/payment-method-id-mapper.js, test/payment/payment-method-mappers/payment-method-id-mapper.spec.js
Added paypalcommerceinline method id into payment mapper.
To make an ability to submit payment in PayPalCommerceButtonStrategy (checkout-sdk-js)
Unit test
Manual tests
=> feat(payment): PAYPAL-1474 added paypalcommerceinline method id into payment mapper file

src/store/v2/mappers/index.js, test/store/v2/mappers/index.spec.js
In case of multi-shipping, we want to send an array of addresses to the `trusted_shipping_address` endpoint instead of a single address.
This is required to allow vaulting cards with multi-shipping.
Screenshots
**Before**
**After (With multiple addresses)**
**After (With single address)**
ping @bigcommerce/payments
=> feat(payments): PAYMENTS-8378 Allow sending multiple addresses to trusted_shipping_address endpoint

src/payment/payment-method-ids.js, src/payment/payment-method-mappers/payment-method-id-mapper.js, test/payment/payment-method-mappers/payment-method-id-mapper.spec.js
Added temporary `PayPalCommerceAlternativeMethodsV2` payment method id to convert it to `PayPalCommerceAlternativeMethods`.
Bigpay client does not work with experiments. Hence we are providing `PayPalCommerceAlternativeMethodsV2` payment method id to detect whenever `PayPalCommerceAlternativeMethods` provider id should be sent to bigpay.
It is a temporary decision due to refactoring on bigpay
Here is a screenshot of provided request data to bigpay:
`paypalcommerce` should be returned if `PAYPAL-1883.paypal-commerce-split-gateway` experiment is off
`paypalcommercealternativemethods` should be returned if `PAYPAL-1883.paypal-commerce-split-gateway` experiment is on
checkout-sdk-js: https://github.com/bigcommerce/checkout-sdk-js/pull/1782
bigcommerce: …
=> feat(payment): PAYPAL-1882 added temporary PayPalCommerceAlternativeMethodsV2 implementation

src/payment/payment-method-ids.js, src/payment/payment-method-mappers/payment-method-id-mapper.js, test/payment/payment-method-mappers/payment-method-id-mapper.spec.js
Removed paypalcommercealternativemethods transformer
It was created as part of paypalcommerce bigpay refactoring. However we found another way, how to deal with our needs without passing paypalcommercealternativemethods provider id to bigpay
Unit tests
=> refactor(payment): PAYPAL-1921 removed paypalcommercealternativemethods transformer

src/payment/payment-method-ids.js, src/payment/payment-method-mappers/payment-method-id-mapper.js, test/payment/payment-method-mappers/payment-method-id-mapper.spec.js
Removed paypalcommerceinline method id from payments mapper
PayPalCommerce Accelerated Checkout V1 feature is deprecated and should be removed.
Unit tests
=> refactor(payment): PAYPAL-2109 removed paypalcommerceinline method id from payments mapper

src/payment/payment-method-ids.js, src/payment/payment-method-mappers/payment-method-id-mapper.js
Added BraintreeAcceleratedCheckout to payment method mapper
To convert BraintreeAcceleratedCheckout to braintree while placing order
Manual tests
=> feat(payment): PAYPAL-2726 added BraintreeAcceleratedCheckout to payment method mapper

commit-validation.json
Updated commit-validation rule from payments to payment
To keep commit-validation rules the same as in checkout projects
-
=> chore(common): PAYPAL-000 updated commit-validation rule from payments to payment

src/payment/v1/payment-mappers/payment-mapper.js, test/mocks/payment-request-data.js, test/payment/v1/payment-mappers/payment-mapper.spec.js
Added token_type to payment mapper
To be able to provider tokenType to backend (bigpay) if needed
Manual tests
=> feat(payment): PAYPAL-2737 added token_type to payment mapper

src/payment/payment-method-ids.js, src/payment/payment-method-mappers/payment-method-id-mapper.js, test/payment/payment-method-mappers/payment-method-id-mapper.spec.js
Added bigcommerce_payments provider mapping
To pass valid BCP provider id in payload to bigpay when customer places order using BCP child modules
Unit tests
=> feat(payment): added bigcommerce_payments provider mapping
